routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//Route::get('/', 'FrontEnd\HomeController@index')->name('home');
//Route::get('page/{slug}', 'FrontEnd\PageController@getPage');
//Route::get('chi-tiet-tin/{slug}', 'FrontEnd\PostController@getDetailNews')->name('detailPost');
//Route::get('event/{slug}', 'FrontEnd\PageController@getDetailEvent')->name('detailEvent');
//Route::get('tin-tuc/{slug}', 'FrontEnd\PostController@getCategoryNews');
//Route::get('giai-phap/{slug}', 'FrontEnd\PageController@getCategorySolution');
//Route::get('course/{slug}', 'FrontEnd\CourseController@getDetailCourse');
//Route::get('search', 'FrontEnd\CourseController@getSearchCourse')->name('search');
//Route::get('ajax/comment', 'FrontEnd\PageController@getCommentByPost')->name('comment');
//Route::post('ajax/save-comment', 'FrontEnd\PageController@saveCommentByPost')->name('save_comment');
//Route::get('ajax/list-course', 'FrontEnd\CourseController@getCourseAjax')->name('list_course');
//Route::get('ajax/category-post', 'FrontEnd\HomeController@getCategoryPosts')->name('category_post');
//Route::get('career/{slug}', 'FrontEnd\PageController@getCareerDetail')->name('career_detail');
//Route::post('contact/', 'FrontEnd\PageController@saveContact')->name('save_contact');
//Route::post('newsletter/', 'FrontEnd\PageController@saveNewsLetter')->name('save_newsletter');
//Route::get('change-language/{slug}', 'FrontEnd\HomeController@changeLanguage')->name('change_language');

Auth::routes();


Route::group(['middleware' => ['auth', 'is_active'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
    Route::get('logout', 'Admin\AdminController@logout')->name('logout');
    // Manage User Account
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('index', 'Admin\UserController@index')->name('index');
        Route::get('create', 'Admin\UserController@create')->name('create');
        Route::post('store', 'Admin\UserController@store')->name('store');
        Route::get('edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\UserController@update')->name('update');
        Route::get('change-password', 'Admin\UserController@getChangePassword')->name('change_password');
        Route::post('update-password', 'Admin\UserController@updatePassword')->name('update_password');
        Route::get('delete/{id}', 'Admin\UserController@destroy')->name('destroy');
    });

    // Manage category
    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('index', 'Admin\CategoryController@index')->name('index');
        Route::get('create', 'Admin\CategoryController@create')->name('create');
        Route::post('store', 'Admin\CategoryController@store')->name('store');
        Route::get('edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\CategoryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\CategoryController@destroy')->name('destroy');
    });

    // Manage post
    Route::group(['prefix' => 'post', 'as' => 'post.'], function () {
        Route::get('index', 'Admin\PostController@index')->name('index');
        Route::get('create', 'Admin\PostController@create')->name('create');
        Route::post('store', 'Admin\PostController@store')->name('store');
        Route::get('edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\PostController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PostController@destroy')->name('destroy');
        Route::post('delete-multiple', 'Admin\PostController@delete')->name('delete');
        Route::post('upload-image', 'Admin\PostController@uploadImage')->name('upload_image');
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected  $table = 'categories';

    protected  $fillable = ['name', 'slug', 'meta_title', 'meta_description', 'meta_keywords', 'img', 'description', 'content', 'ord', 'status', 'menu'];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoryRequest;
use App\Http\Services\CategoryService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    protected $categoryService;
    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
        //view()->share('menuService',$this->menuService);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryService->getCategories();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        //dd($this->categoryService->getLastOrder('categories'));
        $time = time();
        $saveCategory = $this->categoryService->saveCategory($time,$request->all());
        if ($saveCategory) {
            $this->categoryService->uploadImage($time, $request->img, 150, 100, 'category');
            return redirect()->route('admin.category.index')->with(['flash_level' => 'success', 'flash_message' => 'Thêm danh mục thành công']);
        } else {
            return redirect()->route('admin.category.index')->with(['flash_level' => 'danger', 'flash_message' => 'Thêm danh mục thất bại']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryService->getCategory($id);
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        //dd($request->all());
        $category = $this->categoryService->getCategory($id);
        $time = time();
        $updateCategory = $this->categoryService->updateCategory($time,$request->all(),$id);
        if ($updateCategory) {
            if (isset($request->img)) {
                $this->categoryService->uploadImage($time, $request->img, 150, 100, 'category');
                $this->categoryService->deleteImage($category['img']);
            }

            return redirect()->route('admin.category.index')->with(['flash_level' => 'success', 'flash_message' => 'Chỉnh sửa danh mục bài viết thành công']);
        } else {
            return redirect()->route('admin.category.index')->with(['flash_level' => 'danger', 'flash_message' => 'Chỉnh sửa danh mục bài viết thất bại']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->categoryService->getCategory($id);
        $deleteCategory = $this->categoryService->deleteCategory($id);
        if ($deleteCategory) {
            $this->categoryService->deleteImage($category['img']);
            $this->categoryService->deleteCourseHasCategory($category['id']);
            return redirect()->route('admin.category.index')->with(['flash_level' => 'success', 'flash_message' => 'Xóa danh mục bài viết thành công']);
        } else {
            return redirect()->route('admin.category.index')->with(['flash_level' => 'danger', 'flash_message' => 'Xóa danh mục bài viết thất bại']);
        }
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layouts.admin')
@section('title') Quản lý danh mục @endsection
@section('content')
    <div class="">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Thêm mới danh mục</div>
                    <div class="panel-body">
                        <form id="formSubmit" action="{!! route('admin.category.store') !!}" method="POST" enctype="multipart/form-data" novalidate>
                            {!! csrf_field() !!}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <label class="control-label">Tên danh mục</label>
                                            <input type="text" class="form-control @if($errors->first('name')) form-control-danger @endif"
                                                   value="{!! old('name') !!}" name="name" placeholder="Tên " id="nameRecord"/>
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-name">{!! $errors->first('name') !!}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <label class="control-label">Tên danh mục (Tiếng Đức)</label>
                                            <input type="text" class="form-control @if($errors->first('ge_name')) form-control-danger @endif"
                                                   value="{!! old('ge_name') !!}" name="ge_name" placeholder="Tên " id="geNameRecord" />
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-ge-name">{!! $errors->first('ge_name') !!}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <?php
                                                $parentCategories = \App\Http\Services\CategoryService::getCategoryByParent(0);
                                            ?>
                                            <label class="control-label">Danh mục</label>
                                            <select id="category" name="category_id" class="form-control" style="height: auto !important">
                                                <option value="0">-- None --</option>
                                                @foreach($parentCategories as $category)
                                                    <option value="{!! $category->id !!}">{!! $category->name !!}</option>
                                                    <?php
                                                    $childrenCategories = \App\Http\Services\CategoryService::getCategoryByParent($category->id);
                                                    ?>
                                                    @foreach($childrenCategories as $item)
                                                        <option value="{!! $item->id !!}">--{!! $item->name !!}</option>
                                                    @endforeach
                                                @endforeach
{{--                                                    @foreach($parentCategories as $category)--}}
{{--                                                        @if($category->has_children == 1)--}}
{{--                                                            <optgroup label="{!! $category->name !!}" class="group-{!! $category->id !!}">--}}
{{--                                                                <?php--}}
{{--                                                                $childrenCategories = \App\Http\Services\CategoryService::getCategoryByParent($category->id);--}}
{{--                                                                ?>--}}
{{--                                                                @foreach($childrenCategories as $item)--}}
{{--                                                                    <option value="{!! $item->id !!}">{!! $item->name !!}</option>--}}
{{--                                                                @endforeach--}}
{{--                                                            </optgroup>--}}
{{--                                                        @endif--}}
{{--                                                        <optgroup label="{!! $category->name !!}" class="group-{!! $category->id !!}">--}}
{{--                                                            <option value="{!! $category->id !!}">{!! $category->name !!}</option>--}}
{{--                                                        </optgroup>--}}
{{--                                                    @endforeach--}}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-6 form-group">
                                            <div class="checkbox-fade fade-in-primary">
                                                <label>
                                                    <input type="checkbox" value="1" id="status-id" name="status">
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span>Hiển Thị</span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-6 form-group">
                                            <div class="checkbox-fade fade-in-primary">
                                                <label>
                                                    <input type="checkbox" value="1" id="has-children-id" name="has_children">
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span>Chứa danh mục con</span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12 form-group">
                                            <label class="control-label">Ảnh</label>
                                            <input type="file" name="img" id="img">
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-img">{!! $errors->first('img') !!}</span>
                                            </div>
                                            <img id="preview-img" src="{!! asset('images/no-image.png') !!}" class="" width="150" height="100"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label class="control-label">Mô tả danh mục</label>
                                    <textarea class="form-control" id="menuContent" name="content" placeholder="">{!! old('content') !!}</textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label class="control-label">Mô tả danh mục (Tiếng Đức)</label>
                                    <textarea class="form-control" id="menuGeContent" name="ge_content" placeholder="">{!! old('ge_content') !!}</textarea>
                                </div>
                            </div>
                            <div class="row" style="margin-top:20px">
                                <div class="col-xs-12 form-group">
                                    <button type="submit" class="btn btn-success btn-luu" id="btnPrevent">Lưu</button>
                                    <div class="waitting-execute" id="loadingIcon" style="display: none;">
                                        <img src="{!! asset('images/Loading_icon.gif') !!}" style="width:100px;display:block;margin:0 auto;"/>
                                        <p style="text-align:center;color:red;">Vui lòng đợi website xử lý trong giây lát</p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        CKEDITOR.replace('menuGeContent', options);
        CKEDITOR.replace('menuContent', options);
        //upload logo
        $("#img").change(function() {
            readURL(this, 'img');
        });

    </script>

@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.admin')
@section('title') Quản lý danh mục khóa học @endsection
@section('content')
    <div class="">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Chỉnh sửa danh mục khóa học</div>
                    <div class="panel-body">
                        <form id="formSubmit" action="{!! route('admin.category.update', $category['id']) !!}" method="POST" enctype="multipart/form-data" novalidate>
                            {!! csrf_field() !!}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <label class="control-label">Tên danh mục</label>
                                            <input type="text" class="form-control @if($errors->first('name')) form-control-danger @endif"
                                                   value="{!! $category['name'] ? $category['name'] : old('name') !!}" name="name"
                                                   placeholder="Tên " id="nameRecord"/>
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-name">{!! $errors->first('name') !!}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <label class="control-label">Tên danh mục (Tiếng Đức)</label>
                                            <input type="text" class="form-control @if($errors->first('ge_name')) form-control-danger @endif"
                                                   value="{!! $category['ge_name'] ? $category['ge_name'] : old('ge_name') !!}" name="ge_name"
                                                   placeholder="Tên " id="nameGeRecord"/>
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-ge-name">{!! $errors->first('ge_name') !!}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <?php
                                            $parentCategories = \App\Http\Services\CategoryService::getCategoryByParent(0);
                                            ?>
                                            <label class="control-label">Danh mục</label>
                                            <select id="category" name="category_id" class="form-control" style="height: auto !important">
                                                <option value="0" @if($category['parent_id'] == 0) selected @endif>-- None --</option>
                                                @foreach($parentCategories as $parentCategory)
                                                    <option value="{!! $parentCategory->id !!}" @if($category['parent_id'] == $parentCategory->id) selected @endif>{!! $parentCategory->name !!}</option>
                                                    <?php
                                                    $childrenCategories = \App\Http\Services\CategoryService::getCategoryByParent($parentCategory->id);
                                                    ?>
                                                    @foreach($childrenCategories as $item)
                                                        <option value="{!! $item->id !!}" @if($category['parent_id'] == $item->id ) selected @endif>--{!! $item->name !!}</option>
                                                    @endforeach
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-6 form-group">
                                            <div class="checkbox-fade fade-in-primary">
                                                <label>
                                                    <input type="checkbox" value="1" id="status-id" name="status" @if($category['status'] == 1) checked @endif>
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span>Hiển Thị</span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-6 form-group">
                                            <div class="checkbox-fade fade-in-primary">
                                                <label>
                                                    <input type="checkbox" value="1" id="has-children-id" name="has_children" @if($category['has_children'] == 1) checked @endif>
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span>Chứa danh mục con</span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12 form-group">
                                            <label class="control-label">Ảnh</label>
                                            <input type="file" value="{!! $category['img'] !!}" name="img" id="img">
                                            <div class="form-group has-error">
                                                <span class="help-block" id="error-img">{!! $errors->first('img') !!}</span>
                                            </div>
                                            @if(!is_null($category['img']))
                                                <img id="preview-img" src="{!! asset('upload/images/_thumbs/thumb_') !!}{!! $category['img'] !!}"
                                                     class="" width="150" height="100"/>
                                            @else
                                                <img id="preview-img" src="{!! asset('images/no-image.png') !!}" class="" width="150" height="100"/>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label class="control-label">Mô tả danh mục</label>
                                    <textarea class="form-control" id="menuGeContent" name="ge_content" placeholder="">
                                        {!! $category['ge_content'] ? $category['ge_content'] : old('ge_content') !!}
                                    </textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label class="control-label">Mô tả danh mục (Tiếng Đức)</label>
                                    <textarea class="form-control" id="menuContent" name="content" placeholder="">
                                        {!! $category['content'] ? $category['content'] : old('content') !!}
                                    </textarea>
                                </div>
                            </div>
                            <div class="row" style="margin-top:20px">
                                <div class="col-xs-12 form-group">
                                    <button type="submit" class="btn btn-success btn-luu" id="btnPrevent">Lưu</button>
                                    <div class="waitting-execute" id="loadingIcon" style="display: none;">
                                        <img src="{!! asset('images/Loading_icon.gif') !!}" style="width:100px;display:block;margin:0 auto;"/>
                                        <p style="text-align:center;color:red;">Vui lòng đợi website xử lý trong giây lát</p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        CKEDITOR.replace('menuGeContent', options);
        CKEDITOR.replace('menuContent', options);
        //upload logo
        $("#img").change(function() {
            readURL(this, 'img');
        });

    </script>

@endsection