routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//Route::get('/', 'FrontEnd\HomeController@index')->name('home');
//Route::get('page/{slug}', 'FrontEnd\PageController@getPage');
//Route::get('chi-tiet-tin/{slug}', 'FrontEnd\PostController@getDetailNews')->name('detailPost');
//Route::get('event/{slug}', 'FrontEnd\PageController@getDetailEvent')->name('detailEvent');
//Route::get('tin-tuc/{slug}', 'FrontEnd\PostController@getCategoryNews');
//Route::get('giai-phap/{slug}', 'FrontEnd\PageController@getCategorySolution');
//Route::get('course/{slug}', 'FrontEnd\CourseController@getDetailCourse');
//Route::get('search', 'FrontEnd\CourseController@getSearchCourse')->name('search');
//Route::get('ajax/comment', 'FrontEnd\PageController@getCommentByPost')->name('comment');
//Route::post('ajax/save-comment', 'FrontEnd\PageController@saveCommentByPost')->name('save_comment');
//Route::get('ajax/list-course', 'FrontEnd\CourseController@getCourseAjax')->name('list_course');
//Route::get('ajax/category-post', 'FrontEnd\HomeController@getCategoryPosts')->name('category_post');
//Route::get('career/{slug}', 'FrontEnd\PageController@getCareerDetail')->name('career_detail');
//Route::post('contact/', 'FrontEnd\PageController@saveContact')->name('save_contact');
//Route::post('newsletter/', 'FrontEnd\PageController@saveNewsLetter')->name('save_newsletter');
//Route::get('change-language/{slug}', 'FrontEnd\HomeController@changeLanguage')->name('change_language');

Auth::routes();


Route::group(['middleware' => ['auth', 'is_active'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
    Route::get('logout', 'Admin\AdminController@logout')->name('logout');
    // Manage User Account
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('index', 'Admin\UserController@index')->name('index');
        Route::get('create', 'Admin\UserController@create')->name('create');
        Route::post('store', 'Admin\UserController@store')->name('store');
        Route::get('edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\UserController@update')->name('update');
        Route::get('change-password', 'Admin\UserController@getChangePassword')->name('change_password');
        Route::post('update-password', 'Admin\UserController@updatePassword')->name('update_password');
        Route::get('delete/{id}', 'Admin\UserController@destroy')->name('destroy');
    });

    // Manage category
    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('index', 'Admin\CategoryController@index')->name('index');
        Route::get('create', 'Admin\CategoryController@create')->name('create');
        Route::post('store', 'Admin\CategoryController@store')->name('store');
        Route::get('edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\CategoryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\CategoryController@destroy')->name('destroy');
    });

    // Manage post
    Route::group(['prefix' => 'post', 'as' => 'post.'], function () {
        Route::get('index', 'Admin\PostController@index')->name('index');
        Route::get('create', 'Admin\PostController@create')->name('create');
        Route::post('store', 'Admin\PostController@store')->name('store');
        Route::get('edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\PostController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PostController@destroy')->name('destroy');
        Route::post('delete-multiple', 'Admin\PostController@delete')->name('delete');
        Route::post('upload-image', 'Admin\PostController@uploadImage')->name('upload_image');
    });
});

resources/views/admin/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="Phoenixcoded">
    <meta name="keywords" content=", Flat ui, Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="Phoenixcoded">
    <!-- Favicon icon -->

    <link rel="icon" href="{{ asset('admin/images/favicon.ico') }}" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/bootstrap.min.css') }}">

    <script type="text/javascript" src="{{ asset('admin/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('admin/js/bootstrap.min.js') }}"></script>
    <!-- Required Fremwork -->
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/themify-icons.css') }}">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/icofont.css') }}">
    <!-- flag icon framework css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/flag-icon.min.css') }}">
    <!-- Menu-Search css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/component.css') }}">
    <!-- jpro forms css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/demo.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/j-forms.css') }}">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/style.css') }}">
    <!--color css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/css/color-1.css') }}" id="color" />

    <!-- Styles -->
    {{--<link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">

    <link  href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.css" rel="stylesheet">


    <script>
        window.Laravel = <?php echo json_encode(['csrfToken' => csrf_token()]); ?>
    </script>
    <script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
    <script>
        var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
        };
    </script>
    <style>
        button.multiselect b.caret, ul.multiselect-container li span.input-group-addon, ul.multiselect-container li span.input-group-btn {
            display: none !important;
        }

    </style>

</head>
<body class="menu-static">
<div id="">
    <!-- Pre-loader start -->
    <div class="theme-loader">
        <div class="ball-scale">
            <div></div>
        </div>
    </div>
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')
    <div class="main-body">
        <div class="page-wrapper">
            @yield('content')
        </div>
    </div>

</div>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@include('admin.layouts.footer')
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<!-- j-pro js -->
<script type="text/javascript" src="{{ asset('admin/js/jquery.ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/jquery.maskedinput.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/jquery-cloneya.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/autoNumeric.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/jquery.stepper.min.js') }}"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="{{ asset('admin/js/jquery.slimscroll.js') }}"></script>
<!-- modernizr js -->
<script type="text/javascript" src="{{ asset('admin/js/modernizr.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/css-scrollbars.js') }}"></script>
<!-- classie js -->
<script type="text/javascript" src="{{ asset('admin/js/classie.js') }}"></script>
<!-- i18next.min.js -->
<script type="text/javascript" src="{{ asset('admin/js/i18next.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/i18nextXHRBackend.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/i18nextBrowserLanguageDetector.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/jquery-i18next.min.js') }}"></script>
<!-- Custom js -->
<script type="text/javascript" src="{{ asset('admin/js/currency-form.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/script.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/common.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">

resources/views/admin/layouts/header.blade.php
<nav class="navbar header-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="ti-menu"></i>
            </a>
            <a class="mobile-search morphsearch-search" href="#">
                <i class="ti-search"></i>
            </a>
            <a href="index.html">
                <img class="img-fluid" src="{{ asset('admin/images/logo.png') }}" alt="Theme-Logo" />
            </a>
            <a class="mobile-options">
                <i class="ti-more"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <div>
                <ul class="nav-left">
                    <li>
                        <a id="collapse-menu" href="#">
                            <i class="ti-menu"></i>
                        </a>
                    </li>
                    <li>
                        <a class="main-search morphsearch-search" href="#">
                            <!-- themify icon -->
                            <i class="ti-search"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#!" onclick="javascript:toggleFullScreen()">
                            <i class="ti-fullscreen"></i>
                        </a>
                    </li>
                </ul>
                <ul class="nav-right">
                    <li class="user-profile header-notification">
                        <a href="#!">
                            <img src="{{ asset('admin/images/user.png') }}" alt="User-Profile-Image">
                            <span>{!! \Illuminate\Support\Facades\Auth::user()->name !!}</span>
                            <i class="ti-angle-down"></i>
                        </a>
                        <ul class="show-notification profile-notification">
                            <li>
                                <a href="{!! route('admin.user.change_password') !!}">
                                    <i class="ti-user"></i> Profile
                                </a>
                            </li>
                            <li>
                                <a href="{!! route('admin.logout') !!}">
                                    <i class="ti-layout-sidebar-left"></i> Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- search -->
                <!-- search end -->
            </div>
        </div>
    </div>
</nav>

resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu">

    <div class="main-menu-content">
        <ul class="main-navigation">

            <li class="nav-title" data-i18n="nav.category.navigation">
                <i class="ti-line-dashed"></i>
                <span>Navigation</span>
            </li>
            <li class="nav-item @if(Route::currentRouteName() == 'admin.dashboard')has-class @endif">
                <a href="{{ route('admin.dashboard') }}">
                    <i class="ti-home"></i>
                    <span data-i18n="">Dashboard</span>
                </a>
            </li>
            <li class="nav-item @if(Route::currentRouteName() == 'admin.user.index' || Route::currentRouteName() == 'admin.user.create'
            || Route::currentRouteName() == 'admin.user.edit')has-class @endif">
                <a href="{!! route('admin.user.index') !!}">
                    <i class="ti-user"></i>
                    <span data-i18n="nav.page_layout.main">Quản lý tài khoản</span>
                </a>
            </li>

            <li class="nav-item @if(Route::currentRouteName() == 'admin.category.index' || Route::currentRouteName() == 'admin.category.create'
            || Route::currentRouteName() == 'admin.category.edit')has-class @endif">
                <a href="{!! route('admin.category.index') !!}">
                    <i class="ti-menu-alt"></i>
                    <span data-i18n="nav.page_layout.main">Danh mục bài viết</span>
                </a>
            </li>

            <li class="nav-item @if(Route::currentRouteName() == 'admin.post.index' || Route::currentRouteName() == 'admin.post.create'
            || Route::currentRouteName() == 'admin.post.edit')has-class @endif">
                <a href="{!! route('admin.post.index') !!}">
                    <i class="ti-write"></i>
                    <span data-i18n="nav.page_layout.main">Quản lý bài viết</span>
                </a>
            </li>
        </ul>
    </div>
</div>