routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//Route::get('/', 'FrontEnd\HomeController@index')->name('home');
//Route::get('page/{slug}', 'FrontEnd\PageController@getPage');
//Route::get('chi-tiet-tin/{slug}', 'FrontEnd\PostController@getDetailNews')->name('detailPost');
//Route::get('event/{slug}', 'FrontEnd\PageController@getDetailEvent')->name('detailEvent');
//Route::get('tin-tuc/{slug}', 'FrontEnd\PostController@getCategoryNews');
//Route::get('giai-phap/{slug}', 'FrontEnd\PageController@getCategorySolution');
//Route::get('course/{slug}', 'FrontEnd\CourseController@getDetailCourse');
//Route::get('search', 'FrontEnd\CourseController@getSearchCourse')->name('search');
//Route::get('ajax/comment', 'FrontEnd\PageController@getCommentByPost')->name('comment');
//Route::post('ajax/save-comment', 'FrontEnd\PageController@saveCommentByPost')->name('save_comment');
//Route::get('ajax/list-course', 'FrontEnd\CourseController@getCourseAjax')->name('list_course');
//Route::get('ajax/category-post', 'FrontEnd\HomeController@getCategoryPosts')->name('category_post');
//Route::get('career/{slug}', 'FrontEnd\PageController@getCareerDetail')->name('career_detail');
//Route::post('contact/', 'FrontEnd\PageController@saveContact')->name('save_contact');
//Route::post('newsletter/', 'FrontEnd\PageController@saveNewsLetter')->name('save_newsletter');
//Route::get('change-language/{slug}', 'FrontEnd\HomeController@changeLanguage')->name('change_language');

Auth::routes();


Route::group(['middleware' => ['auth', 'is_active'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', 'Admin\AdminController@index')->name('dashboard');
    Route::get('logout', 'Admin\AdminController@logout')->name('logout');
    // Manage User Account
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('index', 'Admin\UserController@index')->name('index');
        Route::get('create', 'Admin\UserController@create')->name('create');
        Route::post('store', 'Admin\UserController@store')->name('store');
        Route::get('edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\UserController@update')->name('update');
        Route::get('change-password', 'Admin\UserController@getChangePassword')->name('change_password');
        Route::post('update-password', 'Admin\UserController@updatePassword')->name('update_password');
        Route::get('delete/{id}', 'Admin\UserController@destroy')->name('destroy');
    });

    // Manage category
    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('index', 'Admin\CategoryController@index')->name('index');
        Route::get('create', 'Admin\CategoryController@create')->name('create');
        Route::post('store', 'Admin\CategoryController@store')->name('store');
        Route::get('edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\CategoryController@update')->name('update');
        Route::get('delete/{id}', 'Admin\CategoryController@destroy')->name('destroy');
    });

    // Manage post
    Route::group(['prefix' => 'post', 'as' => 'post.'], function () {
        Route::get('index', 'Admin\PostController@index')->name('index');
        Route::get('create', 'Admin\PostController@create')->name('create');
        Route::post('store', 'Admin\PostController@store')->name('store');
        Route::get('edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('update/{id}', 'Admin\PostController@update')->name('update');
        Route::get('delete/{id}', 'Admin\PostController@destroy')->name('destroy');
        Route::post('delete-multiple', 'Admin\PostController@delete')->name('delete');
        Route::post('upload-image', 'Admin\PostController@uploadImage')->name('upload_image');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'level', 'status', 'course'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ChangePasswordRequest;
use App\Http\Requests\UserRequest;
use App\Http\Services\UserService;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public $perPage = 10;
    protected $userService;
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
        //view()->share('menuService',$this->menuService);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (isset($_GET['keyword'])) {
            $keyword = $_GET['keyword'];
            $users = $this->userService->getUsers($this->perPage, $keyword);
        } else {
            $users = $this->userService->getUsers($this->perPage, null);
        }
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $saveUser = $this->userService->saveUser($request->all());
        if ($saveUser) {
            return redirect()->route('admin.user.index')->with(['flash_level' => 'success', 'flash_message' => 'Thêm mới tài khoản thành công']);
        } else {
            return redirect()->route('admin.user.index')->with(['flash_level' => 'danger', 'flash_message' => 'Thêm mới tài khoản thất bại']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userService->getUser($id);
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        if (!is_null($request->name)) {
            $updateUser = $this->userService->updateUser($request->all(),$id);
            if ($updateUser) {
                return redirect()->route('admin.user.index')->with(['flash_level' => 'success', 'flash_message' => 'Chỉnh sửa tài khoản thành công']);
            } else {
                return redirect()->route('admin.user.index')->with(['flash_level' => 'danger', 'flash_message' => 'Chỉnh sửa tài khoản thất bại']);
            }
        } else {
            return redirect()->route('admin.user.create')->with(['flash_level' => 'danger', 'flash_message' => 'Vui lòng nhập tên']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleteUser = $this->userService->deleteUser($id);
        if ($deleteUser) {
            return redirect()->route('admin.user.index')->with(['flash_level' => 'success', 'flash_message' => 'Xóa tài khoản thành công']);
        } else {
            return redirect()->route('admin.user.index')->with(['flash_level' => 'danger', 'flash_message' => 'Xóa tài khoản thất bại']);
        }
    }

    public function getChangePassword() {
        $user = Auth::user();
        return view('admin.users.change_password', compact('user'));
    }

    public function updatePassword(ChangePasswordRequest $request)
    {
        $id = Auth::user()->id;
        if (Hash::check($request->newPassword, Auth::user()->getAuthPassword())) {
            $updatePassword = $this->userService->updatePassword($request->all(),$id);
            if ($updatePassword) {
                Auth::logout();
                return redirect()->route('login')->with(['flash_level' => 'success', 'flash_message' => 'Chỉnh sửa tài khoản thành công vui lòng đăng nhập lại']);
            } else {
                return redirect()->route('admin.user.change_password')->with(['flash_level' => 'danger', 'flash_message' => 'Chỉnh sửa tài khoản thất bại']);
            }
        } else {
            return redirect()->route('admin.user.change_password')->with(['flash_level' => 'danger', 'flash_message' => 'Mật khẩu cũ không chính xác']);
        }
    }
}

resources/views/admin/users/change_password.blade.php
@extends('admin.layouts.admin')
@section('title') Thông tin tài khoản @endsection
@section('content')
    <div class="">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Chỉnh sửa tài khoản</div>
                    <div class="panel-body">
                        @if (Session::has('flash_message'))
                            <div class="alert alert-{{ Session::get('flash_level') }} icons-alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <i class="icofont icofont-close-line-circled"></i>
                                </button>
                                <p><strong>{!! Session::get('flash_message') !!}</strong></p>
                            </div>
                        @endif
                        <form id="formSubmit" action="{!! route('admin.user.update_password') !!}" method="POST" novalidate>
                            {!! csrf_field() !!}
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Tên</label>
                                    <input type="text" class="form-control @if($errors->first('name')) form-control-danger @endif"
                                           value="{!! $user['name'] ? $user['name'] : old('name') !!}" name="name" placeholder="Tên " id="nameRecord" onkeyup="generateSlug()"/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-name">{!! $errors->first('name') !!}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Mật khẩu cũ</label>
                                    <input type="password" class="form-control @if($errors->first('password')) form-control-danger @endif"
                                           value="" name="password" placeholder="********" required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-password">{!! $errors->first('password') !!}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Email</label>
                                    <input type="email" class="form-control @if($errors->first('email')) form-control-danger @endif" disabled
                                           value="{!! $user['email'] ? $user['email'] : old('email') !!}" name="email" placeholder="Ex: abc@gmail.com " required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-email">{!! $errors->first('email') !!}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Nhập mật khẩu mới</label>
                                    <input type="password" class="form-control @if($errors->first('newPassword')) form-control-danger @endif"
                                           value="" name="newPassword" placeholder="********" required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-newPassword">{!! $errors->first('newPassword') !!}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row" style="margin-top:20px">
                                <div class="col-xs-12 form-group">
                                    <button type="submit" class="btn btn-success btn-luu" id="btnPrevent">Lưu</button>
                                    <div class="waitting-execute" id="loadingIcon" style="display: none;">
                                        <img src="{!! asset('images/Loading_icon.gif') !!}" style="width:100px;display:block;margin:0 auto;"/>
                                        <p style="text-align:center;color:red;">Vui lòng đợi website xử lý trong giây lát</p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/users/create.blade.php
@extends('admin.layouts.admin')
@section('title') Quản lý tài khoản @endsection
@section('content')
    <div class="">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Thêm mới tài khoản</div>
                    <div class="panel-body">
                        <form id="formSubmit" action="{!! route('admin.user.store') !!}" method="POST" novalidate>
                            {!! csrf_field() !!}
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <div class="row">
                                        <div class="col-md-2 form-group">
                                            <div class="checkbox-fade fade-in-primary" style="margin-top: 35px;">
                                                <label>
                                                    <input type="checkbox" value="1" id="status-id" name="status">
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span>Hiển Thị</span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-10 form-group">
                                            <label class="control-label" style="color: #fff; display: block; width: 100%">Accepted Courses</label>
                                            <select id="courseAccepted" name="courses[]" multiple class="multiple-select-checkboxes">
                                                <optgroup label="Ngữ pháp cơ bản" class="group-1">
                                                    <option value="1-1">Option 1.1</option>
                                                    <option value="1-2">Option 1.2</option>
                                                    <option value="1-3">Option 1.3</option>
                                                    <option value="1-4">Option 1.4</option>
                                                    <option value="1-5">Option 1.5</option>
                                                </optgroup>
                                                <optgroup label="Tình huống hội thoại" class="group-2">
                                                    <option value="2-1">Option 2.1</option>
                                                    <option value="2-2">Option 2.2</option>
                                                    <option value="2-3">Option 2.3</option>
                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Vai trò</label>
                                    <select class="form-control" style="height: auto !important" name="level">
                                        {!! \App\Helpers\Common::getRoleOptions(\Illuminate\Support\Facades\Auth::user()->level, 0) !!}
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Tên</label>
                                    <input type="text" class="form-control @if($errors->first('name')) form-control-danger @endif"
                                           value="{!! old('name') !!}" name="name" placeholder="Tên " id="nameRecord" onkeyup="generateSlug()"/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-name">{!! $errors->first('name') !!}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Mật khẩu</label>
                                    <input type="password" class="form-control @if($errors->first('password')) form-control-danger @endif"
                                           value="{!! old('password') !!}" name="password" placeholder="********" required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-password">{!! $errors->first('password') !!}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Email</label>
                                    <input type="email" class="form-control @if($errors->first('email')) form-control-danger @endif"
                                           value="{!! old('email') !!}" name="email" placeholder="Ex: abc@gmail.com " required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-email">{!! $errors->first('email') !!}</span>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="control-label">Nhập lại mật khẩu</label>
                                    <input type="password" class="form-control @if($errors->first('rePassword')) form-control-danger @endif"
                                           value="{!! old('rePassword') !!}" name="rePassword" placeholder="********" required/>
                                    <div class="form-group has-error">
                                        <span class="help-block" id="error-rePassword">{!! $errors->first('rePassword') !!}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row" style="margin-top:20px">
                                <div class="col-xs-12 form-group">
                                    <button type="submit" class="btn btn-success btn-luu" id="btnPrevent">Lưu</button>
                                    <div class="waitting-execute" id="loadingIcon" style="display: none;">
                                        <img src="{!! asset('images/Loading_icon.gif') !!}" style="width:100px;display:block;margin:0 auto;"/>
                                        <p style="text-align:center;color:red;">Vui lòng đợi website xử lý trong giây lát</p>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#courseAccepted').multiselect({
                nonSelectedText: 'Chọn khoá học được phép tham gia',
                enableClickableOptGroups: true,
                enableCollapsibleOptGroups: true,
                enableFiltering: true,
                includeSelectAllOption: true,
                buttonWidth: '100%',
                numberDisplayed: 5,
                nSelectedText: ' - Khoá học đã được chọn!',
                allSelectedText: 'Tất cả khoá học đã được chọn',
                maxHeight: 500,
            });
        });
    </script>


@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.admin')
@section('title') Quản lý tài khoản @endsection
@section('content')
    <div class="row">
        <div class="col-md-12 form-group">
            @if(\Illuminate\Support\Facades\Auth::user()->level <= 2)
            <a href="{!! route('admin.user.create') !!}" class="btn btn-success">Thêm mới tài khoản</a>
                @endif
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Danh sách tài khoản

        </div>
        <div class="panel-body">

            @if (Session::has('flash_message'))
                <div class="alert alert-{{ Session::get('flash_level') }} icons-alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="icofont icofont-close-line-circled"></i>
                    </button>
                    <p><strong>{!! Session::get('flash_message') !!}</strong></p>
                </div>
            @endif
            <div class="row">
                <div class="col-md-7"></div>
                <div class="col-md-5 form-group">
                    <form method="get" action="{!! route('admin.user.index') !!}">
                        <div class="col-md-9 form-group">
                            <input type="text" class="form-control" name="keyword" id="inputSearch" placeholder="Nhập từ khóa tìm kiếm....."/>
                        </div>
                        <div class="col-md-3 form-group" style="padding-left: 0px;">
                            <button class="btn btn-primary" type="submit"><i class="ti-search"></i> Tìm kiếm</button>
                        </div>
                    </form>
                </div>
            </div>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <td class="text-center text-vertical-align text-bold">STT</td>
                    <td class="text-center text-vertical-align text-bold">Tên tài khoản</td>
                    <td class="text-center text-vertical-align text-bold">Email</td>
                    <td class="text-center text-vertical-align text-bold">Vai trò</td>
                    <td class="text-center text-vertical-align text-bold">Trạng thái</td>
                    <td class="text-center text-vertical-align text-bold">Ngày tạo</td>
                    <td class="text-center text-vertical-align text-bold">Thao tác</td>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $key => $item)
                <tr>
                    <td class="text-center text-vertical-align" style="white-space:normal;text-align: center !important;">
                        {!! $key + 1 !!}
                    </td>
                    <td class="text-center text-vertical-align" style="white-space:normal;text-align: left !important;">
                        {!! $item['name'] !!}
                    </td>
                    <td class="text-center text-vertical-align">
                        {!! $item['email'] !!}
                    </td>
                    <td class="text-center text-vertical-align">
                        @php $k = $item['level'] - 1; @endphp
                        {!! config('role')[$k]['name'] !!}
                    </td>
                    <td class="text-center text-vertical-align">
                        @if($item['status'] == 1)
                            <span class="span-color" style="background: #2ab27b;color:white;padding: 5px;border-radius: 5px;cursor: pointer;"
                                  onclick="changeStatus({!! $item['status'] !!}, {!! $item['id'] !!}, 'users')">Kích hoạt</span>
                        @else
                            <span class="span-color" style="background: grey;color:white;padding: 5px;border-radius: 5px;cursor: pointer;"
                                  onclick="changeStatus({!! $item['status'] !!}, {!! $item['id'] !!}, 'users')">Khóa</span>
                        @endif
                    </td>
                    <td class="text-center text-vertical-align">{!! $item['created_at'] !!}</td>
                    <td class="text-center text-vertical-align">
                        <a href="{!! route('admin.user.edit', $item['id']) !!}"
                           class="btn btn-xs btn-primary">
                            Sửa
                        </a>
                        <a onclick="return confirmDelete('Bạn có chắc muốn xóa bản ghi này không?')"
                           href="{!! route('admin.user.destroy', $item['id']) !!}"
                           class="btn btn-xs btn-danger">
                            Xóa
                        </a>
                    </td>
                </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $users->appends(\Request::all())->links() }}
        </div>
    </div>
    <div class="alert background-success announce">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="icofont icofont-close-line-circled text-white"></i>
        </button>
        <strong>Cập nhật trạng thái thành công</strong>
    </div>
    <div class="alert background-danger announce">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="icofont icofont-close-line-circled text-white"></i>
        </button>
        <strong>Cập nhật trạng thái thất bại</strong>
    </div>
    <style>
        .announce {
            display: none;
            position: fixed;
            top: 75px;
            right: 30px;
        }
        .alert button {
            margin-top: 0px !important;
            margin-left: 30px !important;
        }
    </style>
@endsection